# https://aka.ms/yaml

trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop

variables:
  - group: security-tokens-sbtgen
  - name: COURSIER_CACHE
    value: $(Pipeline.Workspace)/.coursier
  - name: IVY_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.ivy2

jobs:
  - template: .azure-dockerstep.yml
    parameters:
      jobs:
        - job: build_212
          displayName: 'Test & Publish'
          steps:
            - script: |
              bash .build.sh build scripted
            - script: |
              bash .build.sh secrets publish
