// DO NOT EDIT THIS FILE
// IT IS AUTOGENERATED BY `sbtgen.sc` SCRIPT
// ALL CHANGES WILL BE LOST




lazy val `sbt2-core` = project.in(file("lib/sbt2-core"))
  .settings(
    crossScalaVersions := Seq(
      "3.3.7",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind",
    Compile / unmanagedSourceDirectories += baseDirectory.value / ".jvm/src/main/scala" ,
    Compile / unmanagedSourceDirectories ++= (scalaBinaryVersion.value :: CrossVersion.partialVersion(scalaVersion.value).toList.map(_._1))
      .map(v => baseDirectory.value / s".jvm/src/main/scala-$v").distinct,
    Compile / unmanagedResourceDirectories += baseDirectory.value / ".jvm/src/main/resources" ,
    Test / unmanagedSourceDirectories += baseDirectory.value / ".jvm/src/test/scala" ,
    Test / unmanagedSourceDirectories ++= (scalaBinaryVersion.value :: CrossVersion.partialVersion(scalaVersion.value).toList.map(_._1))
      .map(v => baseDirectory.value / s".jvm/src/test/scala-$v").distinct,
    Test / unmanagedResourceDirectories += baseDirectory.value / ".jvm/src/test/resources" ,
    Test / testOptions += Tests.Argument("-oDF")
  )

lazy val `sbt2-api` = project.in(file("lib/sbt2-api"))
  .dependsOn(
    `sbt2-core` % "test->compile;compile->compile"
  )
  .settings(
    crossScalaVersions := Seq(
      "3.3.7",
      "2.13.18"
    ),
    scalaVersion := crossScalaVersions.value.head,
    organization := "io.7mind",
    Compile / unmanagedSourceDirectories += baseDirectory.value / ".jvm/src/main/scala" ,
    Compile / unmanagedSourceDirectories ++= (scalaBinaryVersion.value :: CrossVersion.partialVersion(scalaVersion.value).toList.map(_._1))
      .map(v => baseDirectory.value / s".jvm/src/main/scala-$v").distinct,
    Compile / unmanagedResourceDirectories += baseDirectory.value / ".jvm/src/main/resources" ,
    Test / unmanagedSourceDirectories += baseDirectory.value / ".jvm/src/test/scala" ,
    Test / unmanagedSourceDirectories ++= (scalaBinaryVersion.value :: CrossVersion.partialVersion(scalaVersion.value).toList.map(_._1))
      .map(v => baseDirectory.value / s".jvm/src/test/scala-$v").distinct,
    Test / unmanagedResourceDirectories += baseDirectory.value / ".jvm/src/test/resources" ,
    Test / testOptions += Tests.Argument("-oDF")
  )

lazy val `sbt2-agg` = (project in file(".agg/lib-sbt2-agg"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-core`,
    `sbt2-api`
  )

lazy val `sbt2-agg-jvm` = (project in file(".agg/lib-sbt2-agg-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-core`,
    `sbt2-api`
  )

lazy val `test-sbt2-jvm` = (project in file(".agg/.agg-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-agg-jvm`
  )

lazy val `test-sbt2` = (project in file("."))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    ThisBuild / publishMavenStyle := true,
    crossScalaVersions := Nil,
    scalaVersion := "3.3.7",
    ThisBuild / organization := "io.7mind"
  )
  .disablePlugins(sbt.plugins.JUnitXmlReportPlugin)
  .aggregate(
    `sbt2-agg`
  )
