// DO NOT EDIT THIS FILE
// IT IS AUTOGENERATED BY `sbtgen.sc` SCRIPT
// ALL CHANGES WILL BE LOST


import sbtcrossproject.CrossPlugin.autoImport.{crossProject, CrossType}



lazy val `sbt2-core` = crossProject(JVMPlatform, JSPlatform).crossType(CrossType.Pure).in(file("lib/sbt2-core"))
  .settings(
    libraryDependencies ++= Seq(
      "org.scala-lang.modules" %% "scala-collection-compat" % "2.14.0",
      ("org.scala-lang" %% "scala3-compiler" % "3.3.7").platform(Platform.jvm)
    )
  )
  .settings(
    organization := "io.7mind",
    Test / testOptions += Tests.Argument("-oDF")
  )
  .jvmSettings(
    crossScalaVersions := Seq(
      "3.3.7"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
  .jsSettings(
    crossScalaVersions := Seq(
      "3.3.7"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
lazy val `sbt2-coreJVM` = `sbt2-core`.jvm
lazy val `sbt2-coreJS` = `sbt2-core`.js

lazy val `sbt2-api` = crossProject(JVMPlatform, JSPlatform).crossType(CrossType.Pure).in(file("lib/sbt2-api"))
  .dependsOn(
    `sbt2-core` % "test->compile;compile->compile"
  )
  .settings(
    organization := "io.7mind",
    Test / testOptions += Tests.Argument("-oDF")
  )
  .jvmSettings(
    crossScalaVersions := Seq(
      "3.3.7"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
  .jsSettings(
    crossScalaVersions := Seq(
      "3.3.7"
    ),
    scalaVersion := crossScalaVersions.value.head
  )
lazy val `sbt2-apiJVM` = `sbt2-api`.jvm
lazy val `sbt2-apiJS` = `sbt2-api`.js

lazy val `sbt2-plugin` = project.in(file("sbt-plugins/sbt2-plugin"))
  .settings(
    organization := "io.7mind",
    Test / testOptions += Tests.Argument("-oDF"),
    sbtPlugin := true,
    sbtPluginPublishLegacyMavenStyle := false
  )

lazy val `sbt2-agg` = (project in file(".agg/lib-sbt2-agg"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-coreJVM`,
    `sbt2-coreJS`,
    `sbt2-apiJVM`,
    `sbt2-apiJS`
  )

lazy val `sbt2-agg-jvm` = (project in file(".agg/lib-sbt2-agg-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-coreJVM`,
    `sbt2-apiJVM`
  )

lazy val `sbt2-agg-js` = (project in file(".agg/lib-sbt2-agg-js"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-coreJS`,
    `sbt2-apiJS`
  )

lazy val `sbt2-plugins` = (project in file(".agg/sbt-plugins-sbt2-plugins"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-plugin`
  )

lazy val `sbt2-plugins-jvm` = (project in file(".agg/sbt-plugins-sbt2-plugins-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-plugin`
  )

lazy val `test-sbt2-jvm` = (project in file(".agg/.agg-jvm"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-agg-jvm`
  )

lazy val `test-sbt2-js` = (project in file(".agg/.agg-js"))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    SettingKey[Boolean]("ide-skip-project") := true
  )
  .aggregate(
    `sbt2-agg-js`
  )

lazy val `test-sbt2` = (project in file("."))
  .settings(
    crossScalaVersions := Nil,
    libraryDependencies := Nil,
    publish / skip := true,
    ThisBuild / publishMavenStyle := true,
    crossScalaVersions := Nil,
    scalaVersion := "3.3.7",
    ThisBuild / organization := "io.7mind"
  )
  .disablePlugins(sbt.plugins.JUnitXmlReportPlugin)
  .aggregate(
    `sbt2-agg`
  )
