name: Build

on:
  push:
    branches: [ "develop" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: 17
    - uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-scala
    - name: Build and Test
      run: |
        bash .build.sh build
  test-scripted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-scala
      - name: Build and Test
        run: |
          bash .build.sh scripted
  publish:
    runs-on: ubuntu-latest
    needs: [ 'build', 'test-scripted' ]
    if: secrets.OPENSSL_IV && secrets.OPENSSL_KEY
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-scala
      - name: Publish
        env:
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
        run: |
          bash .build.sh secrets publish
