name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-scala
    - name: Build and Test
      run: |
        bash .build.sh build scripted
    - name: Publish
      run: |
        bash .build.sh secrets publish
