name: Build

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ "develop" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 7mind/github-env@main
      with:
        java-version: 17
    - name: Build and Test
      run: |
        bash .build.sh build
  test-scripted:
    runs-on: ubuntu-latest
    steps:
      - uses: 7mind/github-env@main
        with:
          java-version: 17
      - name: Build and Test
        run: |
          bash .build.sh scripted
  checksecret:
    runs-on: ubuntu-latest
    outputs:
      HAVE_SECRETS: ${{ steps.checksecret_job.outputs.HAVE_SECRETS }}
    steps:
      - id: checksecret_job
        env:
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
        run: |
          echo "HAVE_SECRETS=${{ env.OPENSSL_IV != '' && env.OPENSSL_KEY != '' }}" >> $GITHUB_OUTPUT
  publish:
    runs-on: ubuntu-latest
    needs: [ 'build', 'test-scripted', 'checksecret']
    if: needs.checksecret.outputs.HAVE_SECRETS == 'true'
    steps:
      - uses: 7mind/github-env@main
        with:
          java-version: 17
      - name: Publish
        if: env.HAVE_SECRETS == 'true'
        env:
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
        run: |
          bash .build.sh secrets publish
