name: Build

on:
  push:
    branches: [ "develop" ]
    tags: [ "v**" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: 17
    - uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-scala
    - name: Build and Test
      run: |
        bash .build.sh build
  test-scripted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-scala
      - name: Build and Test
        run: |
          bash .build.sh scripted
  checksecret:
    runs-on: ubuntu-latest
    outputs:
      HAVE_SECRETS: ${{ steps.checksecret_job.outputs.HAVE_SECRETS }}
    steps:
      - id: checksecret_job
        env:
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
        run: |
          echo "::set-output name=HAVE_SECRETS::${{ env.OPENSSL_IV != '' && env.OPENSSL_KEY != '' }}"
          echo "HAVE_SECRETS: $HAVE_SECRETS"
  publish:
    runs-on: ubuntu-latest
    needs: [ 'build', 'test-scripted', 'checksecret']
    if: needs.checksecret.outputs.HAVE_SECRETS == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-scala
      - name: Publish
        if: env.HAVE_SECRETS == 'true'
        env:
          OPENSSL_IV: ${{ secrets.OPENSSL_IV }}
          OPENSSL_KEY: ${{ secrets.OPENSSL_KEY }}
        run: |
          bash .build.sh secrets publish
